### ISSUE TITLE
Install error (Ubuntu 16.04)

### ISSUE THREAD

**Issue by lungsi** [pelednoam/mmvt#18]
Hi,

I am having trouble installing.

I have

_Ubuntu 16.04_
_blender-2.79a-linux-glibc219-x86_64_
_Python 3.5.2_

and cloned the mmvt after which when I run `python3 -m src.setup ` I get

```
➜  mmvt python3 -m src.setup        
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 174, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.5/runpy.py", line 144, in _get_module_details
    code = loader.get_code(mod_name)
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/mmvt_root/mmvt/src/setup.py", line 291
    ''')
      ^
SyntaxError: invalid syntax
➜  mmvt
```

**Comment by pelednoam** [comment]
Hey lungsi,
Thanks for trying to install MMVT!
I enjoyed too much using the f strings, so you can run it only using python 3.6 (https://github.com/pelednoam/mmvt/wiki/Installation). Let me change that, it really doesn't make any sense.

**Comment by pelednoam** [comment]
Ok, I removed the f strings from the setup.py. You can run git pull.
However, there are still some f strings in the preprocessing code. 
Let me know if you stumble across one of them.
To begin with, I'll recommend downloading colin27 and play with it using the exercise we wrote, as explained [here](https://github.com/pelednoam/mmvt#template-brain-and-data).
