### ISSUE TITLE
Installation issue - pip

### ISSUE THREAD

**Issue by moshamss** [pelednoam/mmvt#189]
Hi, 
I have pip installed already but face the following error when entering "python -m src.setup",

"
Traceback (most recent call last):
  File "/home/moe/mmvt_root/mmvt_code/src/setup.py", line 200, in install_reqs
    from pip import main as pipmain
ImportError: No module named 'pip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/moe/blender/2.79/python/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/moe/blender/2.79/python/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/moe/mmvt_root/mmvt_code/src/setup.py", line 459, in <module>
    main(args)
  File "/home/moe/mmvt_root/mmvt_code/src/setup.py", line 374, in main
    install_reqs(args.upgrade_reqs_libs, args.only_verbose)
  File "/home/moe/mmvt_root/mmvt_code/src/setup.py", line 202, in install_reqs
    from pip._internal import main as pipmain
ImportError: No module named 'pip'
{'function': ['all'], 'upgrade_reqs_libs': False, 'overwrite': True, 'links_file_name': 'links.csv', 'overwrite_links': False, 'gui': True, 'blender_fol': '../../blender', 'links': 'links', 'only_verbose': False, 'default_folders': True}  
"
Thank you

**Comment by pelednoam** [comment]
Dear Mohammad, few questions:
1) What operating system are you using?
2) Are you running the python command from the mmvt code folder? Please run "python src/which_python.py " and send me the output.

Thanks,
Noam

**Comment by moshamss** [comment]
Hi Noam,
1. I'm using ubuntu 18.04
2. Yes, I'm running from /mmvt_root/mmvt_code
Location: /home/moe/anaconda3/bin/python
Version: 3.7.0 (default, Jun 28 2018, 13:15:42) 
[GCC 7.2.0]

Thanks,
Moe

**Comment by pelednoam** [comment]
Thanks!
I couldn't replicate this error on my centos7, I'll need to use an Ubuntu virtual box for that.
For now, I've added a fallback, which will just call "pip install -r requirements.txt".
Please rerun the setup and let me know.

Thanks,
Noam

**Comment by alexrockhill** [comment]
It might be helpful to have the full output of the src.setup call because this error might be due to a failure in an earlier step. Can you share that output as well?

**Comment by moshamss** [comment]
I just re-cloned the files, and called the src.setup. so this is the output I get:

{'links': 'links', 'gui': True, 'only_verbose': False, 'default_folders': True, 'function': ['all'], 'overwrite': True, 'blender_fol': '', 'links_file_name': 'links.csv', 'overwrite_links': False, 'upgrade_reqs_libs': False}
Requirement already up-to-date: pip in /home/moe/anaconda3/lib/python3.7/site-packages (18.1)
Requirement already satisfied: numpy in /home/moe/anaconda3/lib/python3.7/site-packages (1.15.1)
Requirement already satisfied: scipy in /home/moe/anaconda3/lib/python3.7/site-packages (1.1.0)
Requirement already satisfied: matplotlib in /home/moe/anaconda3/lib/python3.7/site-packages (2.2.3)
Requirement already satisfied: numpy>=1.7.1 in /home/moe/anaconda3/lib/python3.7/site-packages (from matplotlib) (1.15.1)
Requirement already satisfied: cycler>=0.10 in /home/moe/anaconda3/lib/python3.7/site-packages (from matplotlib) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /home/moe/anaconda3/lib/python3.7/site-packages (from matplotlib) (2.2.0)
Requirement already satisfied: python-dateutil>=2.1 in /home/moe/anaconda3/lib/python3.7/site-packages (from matplotlib) (2.7.3)
Requirement already satisfied: pytz in /home/moe/anaconda3/lib/python3.7/site-packages (from matplotlib) (2018.5)
Requirement already satisfied: six>=1.10 in /home/moe/anaconda3/lib/python3.7/site-packages (from matplotlib) (1.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/moe/anaconda3/lib/python3.7/site-packages (from matplotlib) (1.0.1)
Requirement already satisfied: setuptools in /home/moe/anaconda3/lib/python3.7/site-packages (from kiwisolver>=1.0.1->matplotlib) (40.2.0)
Requirement already satisfied: mne in /home/moe/mne-python (0.17.dev0)
Requirement already satisfied: moviepy in /home/moe/anaconda3/lib/python3.7/site-packages (0.2.3.5)
Requirement already satisfied: imageio<3.0,>=2.1.2 in /home/moe/anaconda3/lib/python3.7/site-packages (from moviepy) (2.4.1)
Requirement already satisfied: tqdm<5.0,>=4.11.2 in /home/moe/anaconda3/lib/python3.7/site-packages (from moviepy) (4.26.0)
Requirement already satisfied: numpy in /home/moe/anaconda3/lib/python3.7/site-packages (from moviepy) (1.15.1)
Requirement already satisfied: decorator<5.0,>=4.0.2 in /home/moe/anaconda3/lib/python3.7/site-packages (from moviepy) (4.3.0)
Requirement already satisfied: nibabel in /home/moe/anaconda3/lib/python3.7/site-packages (2.3.1)
Requirement already satisfied: tables in /home/moe/anaconda3/lib/python3.7/site-packages (3.4.4)
Requirement already satisfied: numpy>=1.8.0 in /home/moe/anaconda3/lib/python3.7/site-packages (from tables) (1.15.1)
Requirement already satisfied: numexpr>=2.5.2 in /home/moe/anaconda3/lib/python3.7/site-packages (from tables) (2.6.8)
Requirement already satisfied: six>=1.9.0 in /home/moe/anaconda3/lib/python3.7/site-packages (from tables) (1.11.0)
Requirement already satisfied: tqdm in /home/moe/anaconda3/lib/python3.7/site-packages (4.26.0)
Requirement already satisfied: Pillow in /home/moe/anaconda3/lib/python3.7/site-packages (5.2.0)
Collecting pysftp
  Using cached https://files.pythonhosted.org/packages/36/60/45f30390a38b1f92e0a8cf4de178cd7c2bc3f874c85430e40ccf99df8fe7/pysftp-0.2.9.tar.gz
Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/tmp/pip-req-tracker-_wj_4h4s/f208bf748412112cca44e09b926e7304fdccf770137694268e9b9a5d'

Requirement already satisfied: scikit_learn in /home/moe/anaconda3/lib/python3.7/site-packages (0.19.2)
Collecting winshell
  Using cached https://files.pythonhosted.org/packages/91/3f/d23d248029a49042d278af9c86b53bc90845e3739a0d7493e00cbac0e4cd/winshell-0.6.zip
Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/tmp/pip-req-tracker-_wj_4h4s/d9dad0b77d0283898ec364c06f41b424a542dad63b2e11b868ebdfc2'

Requirement already satisfied: xlrd in /home/moe/anaconda3/lib/python3.7/site-packages (1.1.0)
Collecting pymsgbox
  Using cached https://files.pythonhosted.org/packages/b6/65/86379ede1db26c40e7972d7a41c69cdf12cc6a0f143749aabf67ab8a41a1/PyMsgBox-1.0.6.zip
Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/tmp/pip-req-tracker-_wj_4h4s/09c7334712f4c14f7877f82e51cdbe4eed756e3a8f9cd4b1ff6f002b'

Collecting zmq
  Using cached https://files.pythonhosted.org/packages/6e/78/833b2808793c1619835edb1a4e17a023d5d625f4f97ff25ffff986d1f472/zmq-0.0.0.tar.gz
Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/tmp/pip-req-tracker-_wj_4h4s/6544c210f8921afc8045475148f8f24300f1ed8b950ec4e02c1e6657'

Requirement already satisfied: pizco in /home/moe/anaconda3/lib/python3.7/site-packages/Pizco-0.1-py3.7.egg (0.1)
Requirement already satisfied: decorator in /home/moe/anaconda3/lib/python3.7/site-packages (4.3.0)
Requirement already satisfied: scikit-learn in /home/moe/anaconda3/lib/python3.7/site-packages (0.19.2)
Requirement already satisfied: scikit-image in /home/moe/anaconda3/lib/python3.7/site-packages (0.14.0)
Requirement already satisfied: matplotlib>=2.0.0 in /home/moe/anaconda3/lib/python3.7/site-packages (from scikit-image) (2.2.3)
Requirement already satisfied: networkx>=1.8 in /home/moe/anaconda3/lib/python3.7/site-packages (from scikit-image) (2.1)
Requirement already satisfied: six>=1.10.0 in /home/moe/anaconda3/lib/python3.7/site-packages (from scikit-image) (1.11.0)
Requirement already satisfied: pillow>=4.3.0 in /home/moe/anaconda3/lib/python3.7/site-packages (from scikit-image) (5.2.0)
Requirement already satisfied: PyWavelets>=0.4.0 in /home/moe/anaconda3/lib/python3.7/site-packages (from scikit-image) (1.0.0)
Requirement already satisfied: dask[array]>=0.9.0 in /home/moe/anaconda3/lib/python3.7/site-packages (from scikit-image) (0.19.1)
Requirement already satisfied: cloudpickle>=0.2.1 in /home/moe/anaconda3/lib/python3.7/site-packages (from scikit-image) (0.5.5)
Requirement already satisfied: numpy>=1.7.1 in /home/moe/anaconda3/lib/python3.7/site-packages (from matplotlib>=2.0.0->scikit-image) (1.15.1)
Requirement already satisfied: cycler>=0.10 in /home/moe/anaconda3/lib/python3.7/site-packages (from matplotlib>=2.0.0->scikit-image) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /home/moe/anaconda3/lib/python3.7/site-packages (from matplotlib>=2.0.0->scikit-image) (2.2.0)
Requirement already satisfied: python-dateutil>=2.1 in /home/moe/anaconda3/lib/python3.7/site-packages (from matplotlib>=2.0.0->scikit-image) (2.7.3)
Requirement already satisfied: pytz in /home/moe/anaconda3/lib/python3.7/site-packages (from matplotlib>=2.0.0->scikit-image) (2018.5)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/moe/anaconda3/lib/python3.7/site-packages (from matplotlib>=2.0.0->scikit-image) (1.0.1)
Requirement already satisfied: decorator>=4.1.0 in /home/moe/anaconda3/lib/python3.7/site-packages (from networkx>=1.8->scikit-image) (4.3.0)
Requirement already satisfied: toolz>=0.7.3; extra == "array" in /home/moe/anaconda3/lib/python3.7/site-packages (from dask[array]>=0.9.0->scikit-image) (0.9.0)
Requirement already satisfied: setuptools in /home/moe/anaconda3/lib/python3.7/site-packages (from kiwisolver>=1.0.1->matplotlib>=2.0.0->scikit-image) (40.2.0)
../mmvt_code/misc/blender.ico
../mmvt_code/src/misc/blender_scripts
../mmvt_code/src/misc/blender_scripts/export_blender_objects.py
../mmvt_code/src/misc/install_blender_reqs.py
../mmvt_code/src/mmvt_addon/scripts/install_blender_reqs.py
../mmvt_code/brainder_scripts/blender_read_annotation.m
find: ‘../../.dbus’../../blender
../../blender/2.79/scripts/addons/io_export_dxf/draw_blenders
../../blender/2.79/scripts/addons/blender_id
../../blender/2.79/scripts/addons/io_blend_utils/blender_bam-unpacked.whl
: Permission denied
find: ‘../../.cache/dconf’: Permission denied
../../.cache/thumbnails/fail/blender
../../.local/share/Trash/expunged/734885999/mmvt_code/src/misc/blender_scripts
../../.local/share/Trash/expunged/652160403/2.79/scripts/addons/io_export_dxf/draw_blenders
../../.local/share/Trash/expunged/652160403/2.79/scripts/addons/blender_id
../../.local/share/Trash/expunged/652160403/2.79/scripts/addons/io_blend_utils/blender_bam-unpacked.whl
../../mmvt_root/mmvt_code/src/misc/blender_scripts
The "mmvt" link was created to /home/moe/mmvt_root/mmvt_blend
The "subjects" link was created to /home/moe/mmvt_root/subjects
The "eeg" link was created to /home/moe/mmvt_root/eeg
The "meg" link was created to /home/moe/mmvt_root/meg
The "fMRI" link was created to /home/moe/mmvt_root/fMRI
The "electrodes" link was created to /home/moe/mmvt_root/electrodes
Coping /home/moe/mmvt_root/mmvt_code/resources/color_maps/hot.npy to /home/moe/mmvt_root/mmvt_blend/color_maps/hot.npy
Coping /home/moe/mmvt_root/mmvt_code/resources/color_maps/tab10.npy to /home/moe/mmvt_root/mmvt_blend/color_maps/tab10.npy
Coping /home/moe/mmvt_root/mmvt_code/resources/color_maps/PuBu.npy to /home/moe/mmvt_root/mmvt_blend/color_maps/PuBu.npy
Coping /home/moe/mmvt_root/mmvt_code/resources/color_maps/jet.npy to /home/moe/mmvt_root/mmvt_blend/color_maps/jet.npy
Coping /home/moe/mmvt_root/mmvt_code/resources/color_maps/PuBu-RdOrYl.npy to /home/moe/mmvt_root/mmvt_blend/color_maps/PuBu-RdOrYl.npy
Coping /home/moe/mmvt_root/mmvt_code/resources/color_maps/BuPu-YlOrRd.npy to /home/moe/mmvt_root/mmvt_blend/color_maps/BuPu-YlOrRd.npy
Coping /home/moe/mmvt_root/mmvt_code/resources/color_maps/YlOrRd.npy to /home/moe/mmvt_root/mmvt_blend/color_maps/YlOrRd.npy
Coping /home/moe/mmvt_root/mmvt_code/resources/color_maps/gray.npy to /home/moe/mmvt_root/mmvt_blend/color_maps/gray.npy
Coping /home/moe/mmvt_root/mmvt_code/resources/color_maps/RdOrYl.npy to /home/moe/mmvt_root/mmvt_blend/color_maps/RdOrYl.npy
Coping /home/moe/mmvt_root/mmvt_code/resources/color_maps/BuPu.npy to /home/moe/mmvt_root/mmvt_blend/color_maps/BuPu.npy
Copying /home/moe/mmvt_root/mmvt_code/resources/aparc.DKTatlas40_groups.csv to /home/moe/mmvt_root/mmvt_blend/aparc.DKTatlas40_groups.csv
Copying /home/moe/mmvt_root/mmvt_code/resources/atlas.csv to /home/moe/mmvt_root/mmvt_blend/atlas.csv
Copying /home/moe/mmvt_root/mmvt_code/resources/sub_cortical_codes.txt to /home/moe/mmvt_root/mmvt_blend/sub_cortical_codes.txt
Copying /home/moe/mmvt_root/mmvt_code/resources/FreeSurferColorLUT.txt to /home/moe/mmvt_root/mmvt_blend/FreeSurferColorLUT.txt
Copying /home/moe/mmvt_root/mmvt_code/resources/empty_subject.blend to /home/moe/mmvt_root/mmvt_blend/empty_subject.blend
Copying /home/moe/mmvt_root/mmvt_code/resources/high_level_atlas.csv to /home/moe/mmvt_root/mmvt_blend/high_level_atlas.csv
Writing output to /home/moe/mmvt_root/mmvt_blend/empty_subject/logs/install_addon.log
"./blender" "/home/moe/mmvt_root/mmvt_blend/empty_subject.blend" --background --python "/home/moe/mmvt_root/mmvt_code/src/mmvt_addon/scripts/install_addon.py" -- --subject "empty_subject" --subjects "" --atlas "dkt" --real_atlas "aparc.DKTatlas40" --bipolar "False" --debug "False" --overwrite "True" --back "True" --python_cmd "/home/moe/anaconda3/bin/python" 
Collecting pip
  Using cached https://files.pythonhosted.org/packages/c2/d7/90f34cb0d83a6c5631cf71dfe64cc1054598c843a92b400e55675cc2ac37/pip-18.1-py2.py3-none-any.whl
Collecting setuptools
  Downloading https://files.pythonhosted.org/packages/e7/16/da8cb8046149d50940c6110310983abb359bbb8cbc3539e6bef95c29428a/setuptools-40.6.2-py2.py3-none-any.whl (573kB)
Collecting wheel
  Downloading https://files.pythonhosted.org/packages/ff/47/1dfa4795e24fd6f93d5d58602dd716c3f101cfd5a77cd9acbe519b44a0a9/wheel-0.32.3-py2.py3-none-any.whl
Installing collected packages: pip, setuptools, wheel
Successfully installed pip-18.1 setuptools-40.6.2 wheel-0.32.3
Collecting matplotlib
  Downloading https://files.pythonhosted.org/packages/ad/4c/0415f15f96864c3a2242b1c74041a806c100c1b21741206c5d87684437c6/matplotlib-3.0.2-cp35-cp35m-manylinux1_x86_64.whl (12.9MB)
Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/tmp/pip-req-tracker-_wj_4h4s/64ed88aed05ef8d46fd172929b61991d5bc6311b777251ebc55dc470'

**Comment by alexrockhill** [comment]
I think the error is due to this previous error:

Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/tmp/pip-req-tracker-_wj_4h4s/64ed88aed05ef8d46fd172929b61991d5bc6311b777251ebc55dc470'

I had experienced similar issues using the MacOS operating system but they were fixed when I upgraded my operating system software.

According to the internet: https://github.com/tensorflow/tensorflow/issues/56 people have experienced similar issues that may be fixed by upgrading pip as in

pip install --upgrade pip

Or you could try running sudo python -m src.setup.

It appears to me to be a file system permissions issue between pip and your operating system. I have also tried using chmod on the /tmp folder in the past but *warning* it may mess up your operating system so I wouldn't do this without backing up everything and trying other options.

**Comment by pelednoam** [comment]
Please try to update the code (git pull) and rerun, I've added the --user flag for the pip install command, that should help. If that won't help, we can do a hangout session.

Best,
Noam

**Comment by moshamss** [comment]
Hi, 
It has changed, however there is still an error, this is the output I'm receiving:
Thank you

{'links': 'links', 'gui': True, 'only_verbose': False, 'default_folders': True, 'function': ['all'], 'overwrite': True, 'blender_fol': '', 'links_file_name': 'links.csv', 'overwrite_links': False, 'upgrade_reqs_libs': False}
Requirement already up-to-date: pip in /home/moe/anaconda3/lib/python3.7/site-packages (18.1)
Requirement already satisfied: numpy in /home/moe/.local/lib/python3.7/site-packages (1.15.4)
Requirement already satisfied: scipy in /home/moe/.local/lib/python3.7/site-packages (1.1.0)
Requirement already satisfied: numpy>=1.8.2 in /home/moe/.local/lib/python3.7/site-packages (from scipy) (1.15.4)
Requirement already satisfied: matplotlib in /home/moe/.local/lib/python3.7/site-packages (3.0.2)
Requirement already satisfied: python-dateutil>=2.1 in /home/moe/.local/lib/python3.7/site-packages (from matplotlib) (2.7.5)
Requirement already satisfied: cycler>=0.10 in /home/moe/.local/lib/python3.7/site-packages (from matplotlib) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/moe/.local/lib/python3.7/site-packages (from matplotlib) (1.0.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /home/moe/.local/lib/python3.7/site-packages (from matplotlib) (2.3.0)
Requirement already satisfied: numpy>=1.10.0 in /home/moe/.local/lib/python3.7/site-packages (from matplotlib) (1.15.4)
Requirement already satisfied: six>=1.5 in /home/moe/.local/lib/python3.7/site-packages (from python-dateutil>=2.1->matplotlib) (1.11.0)
Requirement already satisfied: setuptools in /home/moe/anaconda3/lib/python3.7/site-packages (from kiwisolver>=1.0.1->matplotlib) (40.2.0)
Requirement already satisfied: mne in /home/moe/.local/lib/python3.7/site-packages (0.17.0)
Requirement already satisfied: moviepy in /home/moe/.local/lib/python3.7/site-packages (0.2.3.5)
Requirement already satisfied: tqdm<5.0,>=4.11.2 in /home/moe/.local/lib/python3.7/site-packages (from moviepy) (4.28.1)
Requirement already satisfied: imageio<3.0,>=2.1.2 in /home/moe/.local/lib/python3.7/site-packages (from moviepy) (2.4.1)
Requirement already satisfied: numpy in /home/moe/.local/lib/python3.7/site-packages (from moviepy) (1.15.4)
Requirement already satisfied: decorator<5.0,>=4.0.2 in /home/moe/.local/lib/python3.7/site-packages (from moviepy) (4.3.0)
Requirement already satisfied: pillow in /home/moe/.local/lib/python3.7/site-packages (from imageio<3.0,>=2.1.2->moviepy) (5.3.0)
Requirement already satisfied: nibabel in /home/moe/.local/lib/python3.7/site-packages (2.3.1)
Requirement already satisfied: tables in /home/moe/anaconda3/lib/python3.7/site-packages (3.4.4)
Requirement already satisfied: numpy>=1.8.0 in /home/moe/.local/lib/python3.7/site-packages (from tables) (1.15.4)
Requirement already satisfied: numexpr>=2.5.2 in /home/moe/.local/lib/python3.7/site-packages (from tables) (2.6.8)
Requirement already satisfied: six>=1.9.0 in /home/moe/.local/lib/python3.7/site-packages (from tables) (1.11.0)
Requirement already satisfied: tqdm in /home/moe/.local/lib/python3.7/site-packages (4.28.1)
Requirement already satisfied: Pillow in /home/moe/.local/lib/python3.7/site-packages (5.3.0)
Requirement already satisfied: pysftp in /home/moe/.local/lib/python3.7/site-packages (0.2.9)
Requirement already satisfied: paramiko>=1.17 in /home/moe/.local/lib/python3.7/site-packages (from pysftp) (2.4.2)
Requirement already satisfied: pyasn1>=0.1.7 in /home/moe/.local/lib/python3.7/site-packages (from paramiko>=1.17->pysftp) (0.4.4)
Requirement already satisfied: cryptography>=1.5 in /home/moe/.local/lib/python3.7/site-packages (from paramiko>=1.17->pysftp) (2.4.1)
Requirement already satisfied: bcrypt>=3.1.3 in /home/moe/.local/lib/python3.7/site-packages (from paramiko>=1.17->pysftp) (3.1.4)
Requirement already satisfied: pynacl>=1.0.1 in /home/moe/.local/lib/python3.7/site-packages (from paramiko>=1.17->pysftp) (1.3.0)
Requirement already satisfied: idna>=2.1 in /home/moe/.local/lib/python3.7/site-packages (from cryptography>=1.5->paramiko>=1.17->pysftp) (2.7)
Requirement already satisfied: asn1crypto>=0.21.0 in /home/moe/.local/lib/python3.7/site-packages (from cryptography>=1.5->paramiko>=1.17->pysftp) (0.24.0)
Requirement already satisfied: cffi!=1.11.3,>=1.7 in /home/moe/.local/lib/python3.7/site-packages (from cryptography>=1.5->paramiko>=1.17->pysftp) (1.11.5)
Requirement already satisfied: six>=1.4.1 in /home/moe/.local/lib/python3.7/site-packages (from cryptography>=1.5->paramiko>=1.17->pysftp) (1.11.0)
Requirement already satisfied: pycparser in /home/moe/.local/lib/python3.7/site-packages (from cffi!=1.11.3,>=1.7->cryptography>=1.5->paramiko>=1.17->pysftp) (2.19)
Requirement already satisfied: scikit_learn in /home/moe/.local/lib/python3.7/site-packages (0.20.0)
Requirement already satisfied: scipy>=0.13.3 in /home/moe/.local/lib/python3.7/site-packages (from scikit_learn) (1.1.0)
Requirement already satisfied: numpy>=1.8.2 in /home/moe/.local/lib/python3.7/site-packages (from scikit_learn) (1.15.4)
Requirement already satisfied: winshell in /home/moe/.local/lib/python3.7/site-packages (0.6)
Requirement already satisfied: xlrd in /home/moe/.local/lib/python3.7/site-packages (1.1.0)
Requirement already satisfied: pymsgbox in /home/moe/.local/lib/python3.7/site-packages (1.0.6)
Requirement already satisfied: zmq in /home/moe/.local/lib/python3.7/site-packages (0.0.0)
Requirement already satisfied: pyzmq in /home/moe/.local/lib/python3.7/site-packages (from zmq) (17.1.2)
Requirement already satisfied: pizco in /home/moe/.local/lib/python3.7/site-packages (0.1)
Requirement already satisfied: decorator in /home/moe/.local/lib/python3.7/site-packages (4.3.0)
Requirement already satisfied: scikit-learn in /home/moe/.local/lib/python3.7/site-packages (0.20.0)
Requirement already satisfied: scipy>=0.13.3 in /home/moe/.local/lib/python3.7/site-packages (from scikit-learn) (1.1.0)
Requirement already satisfied: numpy>=1.8.2 in /home/moe/.local/lib/python3.7/site-packages (from scikit-learn) (1.15.4)
Requirement already satisfied: scikit-image in /home/moe/.local/lib/python3.7/site-packages (0.14.1)
Requirement already satisfied: PyWavelets>=0.4.0 in /home/moe/.local/lib/python3.7/site-packages (from scikit-image) (1.0.1)
Requirement already satisfied: matplotlib>=2.0.0 in /home/moe/.local/lib/python3.7/site-packages (from scikit-image) (3.0.2)
Requirement already satisfied: dask[array]>=0.9.0 in /home/moe/.local/lib/python3.7/site-packages (from scikit-image) (0.20.2)
Requirement already satisfied: pillow>=4.3.0 in /home/moe/.local/lib/python3.7/site-packages (from scikit-image) (5.3.0)
Requirement already satisfied: cloudpickle>=0.2.1 in /home/moe/.local/lib/python3.7/site-packages (from scikit-image) (0.6.1)
Requirement already satisfied: six>=1.10.0 in /home/moe/.local/lib/python3.7/site-packages (from scikit-image) (1.11.0)
Requirement already satisfied: scipy>=0.17.0 in /home/moe/.local/lib/python3.7/site-packages (from scikit-image) (1.1.0)
Requirement already satisfied: networkx>=1.8 in /home/moe/.local/lib/python3.7/site-packages (from scikit-image) (2.2)
Requirement already satisfied: numpy>=1.9.1 in /home/moe/.local/lib/python3.7/site-packages (from PyWavelets>=0.4.0->scikit-image) (1.15.4)
Requirement already satisfied: python-dateutil>=2.1 in /home/moe/.local/lib/python3.7/site-packages (from matplotlib>=2.0.0->scikit-image) (2.7.5)
Requirement already satisfied: cycler>=0.10 in /home/moe/.local/lib/python3.7/site-packages (from matplotlib>=2.0.0->scikit-image) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/moe/.local/lib/python3.7/site-packages (from matplotlib>=2.0.0->scikit-image) (1.0.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /home/moe/.local/lib/python3.7/site-packages (from matplotlib>=2.0.0->scikit-image) (2.3.0)
Requirement already satisfied: toolz>=0.7.3; extra == "array" in /home/moe/.local/lib/python3.7/site-packages (from dask[array]>=0.9.0->scikit-image) (0.9.0)
Requirement already satisfied: decorator>=4.3.0 in /home/moe/.local/lib/python3.7/site-packages (from networkx>=1.8->scikit-image) (4.3.0)
Requirement already satisfied: setuptools in /home/moe/anaconda3/lib/python3.7/site-packages (from kiwisolver>=1.0.1->matplotlib>=2.0.0->scikit-image) (40.2.0)
All links exist!
Coping /home/moe/mmvt_root/mmvt_code/resources/color_maps/jet.npy to /home/moe/mmvt_root/mmvt_blend/color_maps/jet.npy
Coping /home/moe/mmvt_root/mmvt_code/resources/color_maps/BuPu-YlOrRd.npy to /home/moe/mmvt_root/mmvt_blend/color_maps/BuPu-YlOrRd.npy
Coping /home/moe/mmvt_root/mmvt_code/resources/color_maps/hot.npy to /home/moe/mmvt_root/mmvt_blend/color_maps/hot.npy
Coping /home/moe/mmvt_root/mmvt_code/resources/color_maps/BuPu.npy to /home/moe/mmvt_root/mmvt_blend/color_maps/BuPu.npy
Coping /home/moe/mmvt_root/mmvt_code/resources/color_maps/PuBu.npy to /home/moe/mmvt_root/mmvt_blend/color_maps/PuBu.npy
Coping /home/moe/mmvt_root/mmvt_code/resources/color_maps/tab10.npy to /home/moe/mmvt_root/mmvt_blend/color_maps/tab10.npy
Coping /home/moe/mmvt_root/mmvt_code/resources/color_maps/gray.npy to /home/moe/mmvt_root/mmvt_blend/color_maps/gray.npy
Coping /home/moe/mmvt_root/mmvt_code/resources/color_maps/PuBu-RdOrYl.npy to /home/moe/mmvt_root/mmvt_blend/color_maps/PuBu-RdOrYl.npy
Coping /home/moe/mmvt_root/mmvt_code/resources/color_maps/YlOrRd.npy to /home/moe/mmvt_root/mmvt_blend/color_maps/YlOrRd.npy
Coping /home/moe/mmvt_root/mmvt_code/resources/color_maps/RdOrYl.npy to /home/moe/mmvt_root/mmvt_blend/color_maps/RdOrYl.npy
Copying /home/moe/mmvt_root/mmvt_code/resources/aparc.DKTatlas40_groups.csv to /home/moe/mmvt_root/mmvt_blend/aparc.DKTatlas40_groups.csv
Copying /home/moe/mmvt_root/mmvt_code/resources/atlas.csv to /home/moe/mmvt_root/mmvt_blend/atlas.csv
Copying /home/moe/mmvt_root/mmvt_code/resources/sub_cortical_codes.txt to /home/moe/mmvt_root/mmvt_blend/sub_cortical_codes.txt
Copying /home/moe/mmvt_root/mmvt_code/resources/FreeSurferColorLUT.txt to /home/moe/mmvt_root/mmvt_blend/FreeSurferColorLUT.txt
Copying /home/moe/mmvt_root/mmvt_code/resources/empty_subject.blend to /home/moe/mmvt_root/mmvt_blend/empty_subject.blend
Copying /home/moe/mmvt_root/mmvt_code/resources/high_level_atlas.csv to /home/moe/mmvt_root/mmvt_blend/high_level_atlas.csv
Writing output to /home/moe/mmvt_root/mmvt_blend/empty_subject/logs/install_addon.log
"./blender" "/home/moe/mmvt_root/mmvt_blend/empty_subject.blend" --background --python "/home/moe/mmvt_root/mmvt_code/src/mmvt_addon/scripts/install_addon.py" -- --subject "empty_subject" --subjects "" --atlas "dkt" --real_atlas "aparc.DKTatlas40" --bipolar "False" --debug "False" --overwrite "True" --back "True" --python_cmd "/home/moe/anaconda3/bin/python" 
Collecting pip
  Using cached https://files.pythonhosted.org/packages/c2/d7/90f34cb0d83a6c5631cf71dfe64cc1054598c843a92b400e55675cc2ac37/pip-18.1-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 18.1
    Uninstalling pip-18.1:

**Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/home/moe/.local/share/Trash/files/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/pip-18.1.dist-info/INSTALLER'
Consider using the `--user` option or check the permissions.

/bin/sh: 1: bin/pip: not found**

**Comment by alexrockhill** [comment]
It looks like it’s an issue with where Blender is being located. I would suggest deleting everything in the mmvt_root/links folder and rerunning. That should make it so that it resestablishes links and doesn’t use any defunct links.

**Comment by pelednoam** [comment]
It seems that it couldn't update pip in Blender. I've changed something in the pip installation, can you please update and rerun? 
I'm really sorry about that, I've installed ubuntu 18.04 and the latest Anaconda and couldn't replicate the error. If this fix won't help, let's do a hangout session where you are sharing your screen and fix that.
