### ISSUE TITLE
numpy installation bug in windows

### ISSUE THREAD

**Issue by pelednoam** [pelednoam/mmvt#192]
Read prefs: C:\Users\peled\AppData\Roaming\Blender Foundation\Blender\2.79\config\userpref.blend
found bundled python: C:\Program Files\Blender Foundation\Blender\2.79\python
Read blend: C:\Users\peled\mmvt_root\mmvt_blend\colin27_dkt.blend
mmvt_root: C:\Users\peled\mmvt_root\mmvt_code\src\mmvt_addon
Traceback (most recent call last):
  File "C:\Users\peled\mmvt_root\mmvt_blend\colin27_dkt.blend\run_mmvt.py", line 13, in <module>
  File "C:\Users\peled\mmvt_root\mmvt_code\src\mmvt_addon\mmvt_addon.py", line 29, in <module>
    import colors_utils
  File "C:\Users\peled\mmvt_root\mmvt_code\src\mmvt_addon\colors_utils.py", line 3, in <module>
    import numpy as np
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\site-packages\numpy\core\__init__.py", line 67, in <module>
    raise ImportError(msg.format(path))
ImportError: Something is wrong with the numpy installation. While importing we detected an older version of numpy in ['C:\\Program Files\\Blender Foundation\\Blender\\2.79\\python\\lib\\site-packages\\numpy']. One method of fixing this is to repeatedly uninstall numpy until none is found, then reinstall this version.

**Comment by pelednoam** [comment]
The only bypass I've found is to reinstall Blender (completely uninstall and install again)
